[package]
name = "api"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
tracing.workspace = true	 
tracing-subscriber.workspace = true 
clap.workspace = true
infapi = { path = "../infapi"}
